apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy.serviceName" . }}
spec:
  type: ClusterIP
  ports:
    - name: {{ include "envoy.portName" . }}
      port: {{ include "envoy.servicePort" . }}
      targetPort: {{ include "envoy.portName" . }}
      protocol: TCP
  selector:
    {{- include "envoy.selectorLabels" . | nindent 4 }}
